### ISSUE TITLE
How/Where can I get redis port number, database, hostname ?

### ISSUE THREAD

**Issue by Chhoeachim** [yiisoft/yii2-redis#107]
It's my first time for using redis cache in Yii2.
I've spent 6h to config but nothing work.
I think the cause is that I'm not sure about port number, database and hostname.
Here is the last result of my configuration.

![capture](https://cloud.githubusercontent.com/assets/8723667/24792482/6107c5ac-1ba8-11e7-87e9-25148426880f.PNG)

And this is the result that I got.

[
![untitled](https://cloud.githubusercontent.com/assets/8723667/24792451/39aa9048-1ba8-11e7-9643-65c2662f8e53.png)
](url)

And this is in the local developement. I am using Wampserver 3.0.6.

**Comment by samdark** [comment]
Do you have Redis running? 6379 is default port.

**Comment by Chhoeachim** [comment]
@samdark How can I know if Redis is running or not?

**Comment by samdark** [comment]
Have you launched it?

**Comment by Chhoeachim** [comment]
I just follow the instructions in the Yii Guide. Honestly it's my first time touching the Redis.
I already install yii2-redis in my project, then I follow the configuration that shown on Yii Site.
If you don't mind, can you tell me step by step about this ?

**Comment by samdark** [comment]
Well, Yii has a driver similar to PDO MySQL. It doesn't provide Redis itself. You need to install and launch it first: https://redis.io/

**Comment by Chhoeachim** [comment]
Thank @samdark. It worked now in my local dev.
And one more thing. Is it ok when I deploy the project on shared hosting ?

**Comment by samdark** [comment]
Yes if there's a Redis available.

**Comment by Chhoeachim** [comment]
What do you mean `if there's a Redis available` ?
Available in my project or in the hosting ?

**Comment by Chhoeachim** [comment]
@samdark And there is one more issue.

When I use yii\caching\FileCache, the performance time is 58ms.
![filecache](https://cloud.githubusercontent.com/assets/8723667/24845697/8cffdcd4-1dde-11e7-94e7-fd7563ff323a.PNG)

But when I use yii\redis\Cache and yii\redis\Session, the performance time is incredibly increase to 1070ms. 
![redis](https://cloud.githubusercontent.com/assets/8723667/24845731/cbb8f69a-1dde-11e7-8c7c-950813e757e3.PNG)

Is there anything wrong with my configuration?

**Comment by cebe** [comment]
looks like you are trying to let redis client connect to your webserver instead to your redis server.
Its a problem with your setup so this is not the right place to discuss that.

**Comment by Chhoeachim** [comment]
@cebe Thank you. I will use the forum next time.
