### ISSUE TITLE
Unknown component ID: redis in console controller

### ISSUE THREAD

**Issue by ak1987** [yiisoft/yii2-redis#109]
### What steps will reproduce the problem?
I  am using websocket (cboden/ratchet component) and want to save messages to redis.
Websocket is lainched via console app.

Code:

```
                $response['msg'] = $data['msg'];
                $response['user'] = $this->chatters[$from->resourceId];
                $response['type'] = 1;
                $this->sendMessageToAll(json_encode($response));
                // save msg
                $msg = new Messages(); // class Messages extends \yii\redis\ActiveRecord
                $msg->text = $data['msg'];
                $msg->user_name = $response['user'];
                $msg->timestamp = time();
                $msg->type = 1;
                $msg->save();
```

### What's expected?
I want to save messages to Redis
### What do you get instead?
Unknown component ID: redis (web app works fine with same code)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 5.6.3 (xampp)
| Operating system | Win 10

**Comment by samdark** [comment]
Do you have redis component defined in console app config?

**Comment by ak1987** [comment]
My bad. I forgot that console / web configs are separated
Sorry for bothering, aftet proper initialization in console config everyhing works fine.
