### ISSUE TITLE
Not between is not working

### ISSUE THREAD

**Issue by ak1987** [yiisoft/yii2-redis#114]
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11.2
| PHP version      | PHP Version 7.1.6
| Operating system | Win10

I see a strange between / not between condition behavior:

Model:

```
class Measurement extends \yii\redis\ActiveRecord
{
    /**
     *      * @return array the list of attributes for this record
     *           */
    public function attributes()
    {
        return ['id', 'point_num', 'speed', 'azimuth', 'range', 'amplitude', 'timestamp'];
    }

    public static function addTestData()
    {
        $point = new Measurement();
        $point->speed = rand(2, 150);
        $point->azimuth = rand(-35, 35);
        $point->range = rand(0, 150);
        $point->amplitude = 0;
        $point->timestamp = 1500903150334;
        return ($point->save());
    }
}
```

After addTestData method execution i have a testing data with timestamp set to 1500903150334.
I noticed that NOT BETWEEN condition is not working properly, as i got NULL result:

`$data = Measurement::find()->where(['not between', 'timestamp', '0', '1'])->asArray()->all();`

So i tried this:

`$data = Measurement::find()->where(['between', 'timestamp', '0', '2500903150333'])->asArray()->all();`

And it worked. 

`$data = Measurement::find()->where(['**not between**', 'timestamp', '0', '2500903150333'])->asArray()->all();`

It also worked, so NOT BETWEEN and BETWEEN queries are the same.

In LuaScriptBuilder.php function buildBetweenCondition is used both for between and not between conditions, so it must be updated to work with "NOT" operator
buildBetweenCondition

**Comment by cebe** [comment]
fixed, thanks for reporting!

**Comment by coderovich** [comment]
faced the same problem in Yii2 2.0.13.1 PHP 7.1.13

```
 class ProxyQuery extends ActiveQuery {
     public function active() {
         $this->where( ['not between', 'freezed_at', '1', '999999']  );
         return $this;
     }
 }
```

throws an exception

```
Database Exception – yii\db\Exception
Redis error: ERR Error running script (call to f_0586bd8c0bff78e7accee33850a74e30041e4466): @user_script:10: user_script:10: attempt to compare string with boolean 
Redis command was: EVAL local allpks=redis.call('LRANGE','proxy',0,-1)
local pks={}
local n=0
local v=nil
local i=0
local key='proxy'
for k,pk in ipairs(allpks) do
local cfreezed_at0=redis.call('HGET','proxy' .. ':a:' .. pk, 'freezed_at')

if not (cfreezed_at0 >= '1' and cfreezed_at0 <= '999999') then
i=i+1
if i>0 then
n=n+1 pks[n]=redis.call('HGETALL','proxy:a:' .. pk)
end
end
end
return pks 0
```

**Comment by cebe** [comment]
which version of yii2-redis is that?

**Comment by coderovich** [comment]
yiisoft/yii2-redis | 2.0.7.0

Redis 3.2 x64

**Comment by coderovich** [comment]
yep, looks like it's my fault :( sorry
