### ISSUE TITLE
why yiisoft/yii2-redis is so slow??

### ISSUE THREAD

**Issue by baizhiqiang** [yiisoft/yii2-redis#115]
when I use yii2-redis in this code
 `$startTime = microtime(true);
        $rsp = Yii::$app->redis->get('key');
        $endTime = microtime(true);
        $elapsed = number_format($endTime - $startTime, 4);
        echo $elapsed;`
It is slow ,used about one second,

but when I use php_redis.dll ext(not use Yii2), it is fast.
`$startTime = microtime(true);
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$rsp = $redis->get('key');
$endTime = microtime(true);
$elapsed = number_format($endTime - $startTime, 4);
echo $elapsed;`

why this???

| Q                | A
| ---------------- | ---
| Yii vesion    2.0.12   |
| PHP version      7.0 |
| Operating system win7 64bit|

**Comment by cebe** [comment]
does not happen for me, can you show the redis connection config?

**Comment by baizhiqiang** [comment]
I have find the reason,on win7 64bit system,you should always use 127.0.0.1,not localhost. It is about one second slow using localhost because of ipv6.

**Comment by samdark** [comment]
Can't be fixed within Yii.

**Comment by lex10000** [comment]
> I have find the reason,on win7 64bit system,you should always use 127.0.0.1,not localhost. It is about one second slow using localhost because of ipv6.

Thanks a lot, its all that i need for my problem!
