### ISSUE TITLE
pconnect support?

### ISSUE THREAD

**Issue by bobzhangyong** [yiisoft/yii2-redis#12]
Does it support redis pconnect ? I read src code, it seems not support pconnect, do you have any plan to support it ?

**Comment by bazilio91** [comment]
Pretty dangerous feature. We should manage persistent connection pool for php-fpm(cgi) like apis. Just look into phpredis source https://github.com/phpredis/phpredis/blob/develop/redis_session.c

**Comment by samdark** [comment]
@bazilio91 by dangerous you mean eating too many resources?

**Comment by bazilio91** [comment]
@samdark watch this :) http://profyclub.ru/docs/145

**Comment by samdark** [comment]
EPIC intro :) Overall yeah, pconnect could be unstable.

**Comment by Shkarbatov** [comment]
I have more then 2 000 requests per sec. 
Without persistant connect it can eats all socket connections.

Any one work with php + Redis in highload projects? Maby there another one

**Comment by cebe** [comment]
This is already supported via `STREAM_CLIENT_PERSISTENT` option at `$socketClientFlags`.
