### ISSUE TITLE
Integrating with yii\data\ActiveDataProvider, strange error!!!

### ISSUE THREAD

**Issue by phuczeero** [yiisoft/yii2-redis#123]
### What steps will reproduce the problem?
Redis mock data:

id | user_id | ip_address
-- | -------- | -----------
abc | 1 | 172.x.x.x
def | 2 | 172.x.x.x

My model:
```
<?php

namespace common\models;

class Token extends \yii\redis\ActiveRecord
{
    public function attributes()
    {
        return ['id', 'user_id', 'ip_address'];
    }
}
```

My controller:
```
<?php

namespace api\modules\v3\controllers;

use common\models\Token;
use Yii;
use yii\data\ActiveDataProvider;

class TokenController extends \yii\rest\ActiveController
{
    public $modelClass = 'common\models\Token';

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions;
    }

    public function actionIndex()
    {
        $query = Token::find();
        // $query->all(); // 2 records
        $provider = new ActiveDataProvider([
            'query' => $query,
        ]);
        // var_dump($provider->getModels()); // 2 records

        $query = Token::find()->where(['user_id' => 1]);
        // $query->all(); // 1 record
        $provider = new ActiveDataProvider([
            'query' => $query
        ]);
        // var_dump($provider->getModels()); // 0 record

        return $provider;
    }
}
```
### What's expected?
**1 record** in data provider when use `$query->where(['user_id' => 1])`
### What do you get instead?
**0 record**

### Additional info
I see this in Guide article

> By default, yii\data\ActiveDataProvider uses the db application component as the database connection. You may use a different database connection by configuring the yii\data\ActiveDataProvider::$db property.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.1.9
| Operating system | Apache/2.4.10 (Debian)

**Comment by cebe** [comment]
fixed, thanks for reporting!
