### ISSUE TITLE
ActiveRecord does not work with ActiveDataProvider

### ISSUE THREAD

**Issue by nnrudakov** [yiisoft/yii2-redis#129]
### What steps will reproduce the problem?
```php
use yii\redis\ActiveRecord;
class ClassA extends ActiveRecord
{
    public function attributes(): array
    {
        return ['id', 'attr'];
    }
}
$a = (new ClassA(['attr' => 1]))->save();
$query = ClassA::find()->where(['attr' => 1]);
$dataProvider = new \yii\data\ActiveDataProvider(['query' => $query]);
echo GridView::widget([
    'dataProvider' => $dataProvider
]);
```
### What's expected?
Models list.
### What do you get instead?
Empty list.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13
| Yii redis       | 2.0.6

It's because of [ActiveDataProvider->prepareTotalCount()](https://github.com/yiisoft/yii2/blob/master/framework/data/ActiveDataProvider.php#L169). It set wrong limit and offset for query:
```php
$query->limit(-1)->offset(-1)
```
And then [yii\redis\LuaScriptBuilder->build()](https://github.com/yiisoft/yii2-redis/blob/master/LuaScriptBuilder.php#L160) set wrong limit condition:
```php
$limitCondition = 'i>' . $start . ($query->limit === null ? '' : ' and i<=' . ($start + $query->limit));
// it executes like
// if i>-1 and i<=-2 then ...
// and never be true
```
So, total count is 0 and models list is empty.

### My solution

I'm not sure that is correct by Yii rules, but I extend ActiveDataProvider and change prepareTotalCount just remove setting limit and offset:
```php
return (int) $query->orderBy([])->count('*', $this->db);
```

**Comment by cebe** [comment]
the latest version of the code checks for limit < 0:

https://github.com/yiisoft/yii2-redis/blob/8c2653d46bc4f9dd70e604fca3cd512aaa85fdb6/LuaScriptBuilder.php#L154

Can you try with the latest master version and check if it works for you?

**Comment by nnrudakov** [comment]
Yes, it works with the latest changes.
Thanks.
