### ISSUE TITLE
Why not support <, > and <=, >=. but support between?

### ISSUE THREAD

**Issue by netyum** [yiisoft/yii2-redis#13]
rt.

**Comment by cebe** [comment]
good point, arbitrary operator support came to SQL AR after redis was created.

**Comment by ak1987** [comment]
So does <,>, etc. work now?

**Comment by cebe** [comment]
have you tried? Afaik it does not.

**Comment by nailfor** [comment]
LuaScriptBuilder:
`    /**
     * Parses the condition specification and generates the corresponding Lua expression.
     * @param string|array $condition the condition specification. Please refer to [[ActiveQuery::where()]]
     * on how to specify a condition.
     * @param array $columns the list of columns and aliases to be used
     * @return string the generated SQL expression
     * @throws \yii\db\Exception if the condition is in bad format
     * @throws \yii\base\NotSupportedException if the condition is not an array
     */
    public function buildCondition($condition, &$columns)
    {
        static $builders = [
            'not' => 'buildNotCondition',
            'and' => 'buildAndCondition',
            'or' => 'buildAndCondition',
            'between' => 'buildBetweenCondition',
            'not between' => 'buildBetweenCondition',
            'in' => 'buildInCondition',
            'not in' => 'buildInCondition',
            'like' => 'buildLikeCondition',
            'not like' => 'buildLikeCondition',
            'or like' => 'buildLikeCondition',
            'or not like' => 'buildLikeCondition',
            '>' => 'buildGreatCondition',
            '>=' => 'buildGreatEqualCondition',
            '<' => 'buildBelowCondition',
            '<=' => 'buildBelowEqualCondition',
        ];

        if (!is_array($condition)) {
            throw new NotSupportedException('Where condition must be an array in redis ActiveRecord.');
        }
        if (isset($condition[0])) { // operator format: operator, operand 1, operand 2, ...
            $operator = strtolower($condition[0]);
            if (isset($builders[$operator])) {
                $method = $builders[$operator];
                array_shift($condition);

                return $this->$method($operator, $condition, $columns);
            } else {
                throw new Exception('Found unknown operator in query: ' . $operator);
            }
        } else { // hash format: 'column1' => 'value1', 'column2' => 'value2', ...

            return $this->buildHashCondition($condition, $columns);
        }
    }    

    /**
     * Adds a column to the list of columns to retrieve and creates an alias
     * @param string $column the column name to add
     * @param array $columns list of columns given by reference
     * @return string the alias generated for the column name
     */
    private function addColumn($column, &$columns)
    {
        if (isset($columns[$column])) {
            return $columns[$column];
        }
        $name = 'c' . preg_replace("/[^A-z]+/", "", $column) . count($columns);

        return $columns[$column] = $name;
    }
    
    private function buildBelowCondition($operator, $operands, &$columns)
    {
        if (!isset($operands[0], $operands[1])) {
            throw new Exception("Operator '$operator' requires two operands.");
        }

        list($column, $value) = $operands;

        $value = $this->quoteValue($value);
        $column = $this->addColumn($column, $columns);

        return "$column < $value";
    }    
    
    private function buildBelowEqualCondition($operator, $operands, &$columns)
    {
        if (!isset($operands[0], $operands[1])) {
            throw new Exception("Operator '$operator' requires two operands.");
        }

        list($column, $value) = $operands;

        $value = $this->quoteValue($value);
        $column = $this->addColumn($column, $columns);

        return "$column <= $value";
    }    

    private function buildGreatCondition($operator, $operands, &$columns)
    {
        if (!isset($operands[0], $operands[1])) {
            throw new Exception("Operator '$operator' requires two operands.");
        }

        list($column, $value) = $operands;

        $value = $this->quoteValue($value);
        $column = $this->addColumn($column, $columns);

        return "$column > $value";
    }    
    
    private function buildGreatEqualCondition($operator, $operands, &$columns)
    {
        if (!isset($operands[0], $operands[1])) {
            throw new Exception("Operator '$operator' requires two operands.");
        }

        list($column, $value) = $operands;

        $value = $this->quoteValue($value);
        $column = $this->addColumn($column, $columns);

        return "$column >= $value";
    }   `

**Comment by cebe** [comment]
@nailfor could you send that as a pull request?

**Comment by nailfor** [comment]
хорошо, сейчас сделаю реквест...

**Comment by zacksleo** [comment]
Is there any new progress?
