### ISSUE TITLE
Yii2在beanstalk队列中使用Redis Socket连接丢失

### ISSUE THREAD

**Issue by Amniversary** [yiisoft/yii2-redis#133]
在使用beanstalk时 连接大概2天时间左右 请求的数据会发生报错:
`Failed to read from socket.`
`Redis command was: LRANGE red_user_137 0 -1`
`DB Error job is decaying.`
`PS:`
`throw new Exception("Failed to read from socket.\nRedis command was: " . $command);`
提示显示连接错误或丢失, 在php.ini 中把default_socket_timeout设置成 -1 仍然无效
在代码中也设置了 ini_set('default_socket_timeout', -1); 
想知道该怎么解决, 或者有没有办法实现重连机制.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.8-dev
| PHP version      | 5.6.31
| Operating system | CentOS7.0

**Comment by cebe** [comment]
this is probably not about the `default_socket_timeout` in PHP but the `timeout` config in your redis server. Could you try to set `timeout` to 0 in redis.conf and see if that helps?

You may also set `$retries` property on the redis connection:

https://github.com/yiisoft/yii2-redis/blob/master/Connection.php#L295-L301
