### ISSUE TITLE
Does the yii2 redis support the cluster?

### ISSUE THREAD

**Issue by zyb707** [yiisoft/yii2-redis#134]
Does the yii2 redis support the cluster?
if have ,what can we set the config?

**Comment by samdark** [comment]
Only in master: https://github.com/yiisoft/yii2-redis/commit/b5fbd9462178486263239024fc22a50461ae86c1. There's no release for it yet.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2-redis/blob/b5fbd9462178486263239024fc22a50461ae86c1/Cache.php#L56-L76

**Comment by zyb707** [comment]
sorry ,I mean is: Separation of reading and writing and the reading  support the cluster

**Comment by cebe** [comment]
as far as I understand that is exactly what `replicas` property does.

**Comment by zyb707** [comment]
OK， I kown. thx
