### ISSUE TITLE
about yii2-redis and redis-cluster

### ISSUE THREAD

**Issue by sodowe666** [yiisoft/yii2-redis#143]
how to config the redis component to use redis-cluster . I want to shard the redis  . 5 master redis service . not 1 master 4 replicas

**Comment by cebe** [comment]
is this what you mean? https://www.yiiframework.com/extension/yiisoft/yii2-redis/doc/api/2.0/yii-redis-cache#$replicas-detail

**Comment by ruikc** [comment]
how to config  5 master and 5 slave with cluster model
