### ISSUE TITLE
how to use yii2 redis hmget

### ISSUE THREAD

**Issue by yumin5723** [yiisoft/yii2-redis#151]
i want to execute command "HMGET auto:tag>objects 3001172 3001163 3000902 3000893" it works in redis client，but in yii2 when "3001172 3001163 3000902 3000893" is variable，such as 
$range = "3001172,3001163,3000902,3000893";
$redis->executeCommand('HMGET',[$this->MetaKey('objects') ,$range]);

it dose not work, How can i use this hmget

**Comment by cebe** [comment]
this should work:

```php
$args = [$this->MetaKey('objects'), 3001172, 3001163, 3000902, 3000893];
$redis->executeCommand('HMGET', $args);
```
