### ISSUE TITLE
how to use transaction by yii2-redis?

### ISSUE THREAD

**Issue by gloomylad** [yiisoft/yii2-redis#153]
### What steps will reproduce the problem?
1.
Yii::$app->redis
	->multi()
	->set('name','hello')
	->get('name')
	->set('nick','world')
	->get('nick')
	 ->exec();
PHP Fatal Error – yii\base\ErrorException
Call to a member function set() on boolean

2.
Yii::$app->redis->multi();
Yii::$app->redis->set('name','hello');
Yii::$app->redis->get('name');
Yii::$app->redis->set('nick','world');
Yii::$app->redis->get('nick');
Yii::$app->redis->exec();

Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: yii\web\Application::redis
### What's expected?
Are there any examples ?

**Comment by rob006** [comment]
> Yii::$app->redis->exec();
> 
> Unknown Property – yii\base\UnknownPropertyException
> Getting unknown property: yii\web\Application::redis

It looks like you don't have configured `redis` component in your app.

**Comment by gloomylad** [comment]
@rob006 
it's my fault
I'm doing a return here Yii::$app->redis->exec();
So, throw an error
Invalid Parameter – yii\base\InvalidParamException
Response content must not be an array.

**It should look something like this**
Yii::$app->redis->multi();
......
Yii::$app->redis->exec();
return true;

**Not like that**
return Yii::$app->redis->exec();
