### ISSUE TITLE
$redis->mget report an error

### ISSUE THREAD

**Issue by easy09** [yiisoft/yii2-redis#158]
### What steps will reproduce the problem?
`$redis->mget($keys);` report error:
> "yii\base\ErrorException: mb_strlen() expects parameter 1 to be string, array given in D:\sites\xxxxxx\vendor\yiisoft\yii2-redis\src\Connection.php:670

### What do you get instead?
`$redis->executeCommand('mget', $keys);`
is ok

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.15.1
| PHP version      |7.1
| Operating system | windows

**Comment by samdark** [comment]
Do you want to fix it and send us a pull request?

**Comment by rob006** [comment]
This is expected and documented - keys should be specified as separate arguments of method:

    $redis->mget(...$keys);
