### ISSUE TITLE
What happens when the cache expires?

### ISSUE THREAD

**Issue by tehmaestro** [yiisoft/yii2-redis#16]
Hi. I was wondering what happens when the cache is expired. Does Yii call the flush method? Are the values deleted from the cache.
  For example, in an AWS Environment, with ElastiCache Redis, configures with Yii, does Yii delete the redis cache from aws when it has expired?

Thanks.

**Comment by klimov-paul** [comment]
@tehmaestro, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by cebe** [comment]
@tehmaestro expiry of a cache value usually means the cache engine will delete the record. Please refer to the documentation of the cache system for more details.
