### ISSUE TITLE
Redis reconnect error

### ISSUE THREAD

**Issue by kshart** [yiisoft/yii2-redis#176]
#### Problem
 * If `retries` = 0 then `Connection::executeCommand` on throwing `SocketException` will never close the connection and will not open [in code](https://github.com/yiisoft/yii2-redis/blob/ac8f7b75df9837d5b2a0f1cafa22cb815b9623a0/src/Connection.php#L697)
 * If `retries` > 0 and an error will occur when `Connection::open`,
 `retries` will always be 0 and (see item number 1) [in code](https://github.com/yiisoft/yii2-redis/blob/ac8f7b75df9837d5b2a0f1cafa22cb815b9623a0/src/Connection.php#L692)

#### What's expected?
For `retries` = 0 in case of errors in `Connection::executeCommand` close connection
For `retries` > 0 in case of errors in `Connection::executeCommand` do not write zero in `retries`

#### What do you get instead?
For `retries` = 0 in case of errors in `Connection::executeCommand` connection does not close
For `retries` > 0 in case of errors in `Connection::executeCommand` in `retries` it is written zero

#### Проблема
 * Если `retries` = 0 то `Connection::executeCommand` при `SocketException` никогда не закроет соединение и соответственно не откроет [место в коде](https://github.com/yiisoft/yii2-redis/blob/ac8f7b75df9837d5b2a0f1cafa22cb815b9623a0/src/Connection.php#L697)
 * Если `retries` > 0 и при Connection::open произойдет ошибка,
 `retries` будет всегда 0 и (смотреть пункт №1) [место в коде](https://github.com/yiisoft/yii2-redis/blob/ac8f7b75df9837d5b2a0f1cafa22cb815b9623a0/src/Connection.php#L692)

#### Что ожидается?
для `retries` = 0 при ошибках в `Connection::executeCommand` закрывать соединение
для `retries` > 0 при ошибках в `Connection::executeCommand` не обнулять `retries`

#### Что вы получаем вместо этого?
для `retries` = 0 при ошибках в `Connection::executeCommand` соединение не закрывается
для `retries` > 0 при ошибках в `Connection::executeCommand` обнуляется `retries`

Additional info

Q | A
-- | --
Yii vesion | 2.0.14.2
PHP version | 7.2.10
Operating system | Ubuntu 18.04.1
Yii2-redis | 2.0.9

**Comment by cebe** [comment]
> ####
> 
>     * If `retries` = 0 then `Connection::executeCommand` on throwing `SocketException` will never close the connection and will not open [in code](https://github.com/yiisoft/yii2-redis/blob/ac8f7b75df9837d5b2a0f1cafa22cb815b9623a0/src/Connection.php#L697)

this is expected, if you do not tell it to retry, it does not retry.

>  For retries > 0 in case of errors in Connection::executeCommand do not write zero in retries

I agree that this should be fixed.
