### ISSUE TITLE
yii cache/flush-all is dangerous

### ISSUE THREAD

**Issue by shushenghong** [yiisoft/yii2-redis#182]
if use redis as cache,  yii cache/flush-all is very dangerous, since it will flushdb, if there are other data inside the same redis db, they all be cleared.

![image](https://user-images.githubusercontent.com/3275714/58247600-a47c1700-7d8c-11e9-8d1a-40081b2c1f7f.png)

**Comment by samdark** [comment]
@shushenghong is there any safer approach?

**Comment by shushenghong** [comment]
i suggest use scan command with keyPrefix,
and set default keyPrefix like redis session.

```
loop
    scan cursor match keyPrefix* count 100
    del key1 key2 ...
```

**Comment by samdark** [comment]
How would that work with thousands of keys?

**Comment by shushenghong** [comment]
another suggestion, if we use redis hashes to store cache, one hash store no more than 200 fields e.g., so we can avoid this problem?

**Comment by samdark** [comment]
That would require changing the way cache is stored significantly. I'm not sure about performance of such solution compared to current one.

**Comment by flaviovs** [comment]
This is a serious issue, and deserves at least a huge red bold warning in the documentation while not fixed. I our case, we do not use any app data in Redis, but we do use the extension to store cache entries **and** session and mutexes. Needless to say, wiping out the latter have huge implications.

BTW, a workaround we're using here is to use a Redis "database" only for cache components. That way, flushing caches doesn't affect sessions and mutexes.

**Comment by rob006** [comment]
PR: https://github.com/yiisoft/yii2-redis/pull/200
