### ISSUE TITLE
how to use redis setOption()?

### ISSUE THREAD

**Issue by uRoft** [yiisoft/yii2-redis#184]
### What steps will reproduce the problem?
I use yii-redis hscan commands to foreach data. 
### What's expected?
but php allow memory.
### What do you get instead?
The possible reason is that no client options are set.
$redis->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);
### Additional info
how to set it?
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.20
| PHP version      | 7.2.7
| Operating system |Linux

**Comment by uRoft** [comment]
sorry，I found its code problems

**Comment by TsaiQuinn** [comment]
yii2的redis怎么没有setOption 方法呢？
