### ISSUE TITLE
getIsActive() returns true when socket is not connected

### ISSUE THREAD

**Issue by rendong237** [yiisoft/yii2-redis#191]
### What steps will reproduce the problem?

```php
public function getIsActive()
{
        return ArrayHelper::getValue($this->_pool, "$this->hostname:$this->port") !== false;
}
```

if before open, invoke getIsActive() return true

if extend connection,require invoke getIsActive to check connection
### What's expected?
false

### What do you get instead?
true

### Additional info

1. ArrayHelper::getValue($this->_pool, "$this->hostname:$this->port") is null
2. null !== false
3. return true

| Q                | A
| ---------------- | ---
| Yii vesion       | yii-redis 2.0.11
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
@rendong237 thanks for report. Do you want to fix and do a pull request?
