### ISSUE TITLE
Upgrade Question

### ISSUE THREAD

**Issue by JimChenWYU** [yiisoft/yii2-redis#194]
Hi, my yii2-redis version is 2.0.5, now I want to upgrade to the lastest version, but I just find the upgrade readme tell me how to upgrade from 2.0.10, so I can upgrade to 2.0.10 directly and then upgrade to the lastest version by the readme file or not?

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.31
| PHP version      | 7.0
| Operating system | Ubuntu18.04

**Comment by samdark** [comment]
Upgrade notes are cumulative so upgrade to the latest version right away but consider what's written for everything between your version and latest. In case of yii2-redis, that's 2.0.10 notes.
