### ISSUE TITLE
config 'database' does not work

### ISSUE THREAD

**Issue by DesRodman** [yiisoft/yii2-redis#209]
Hello team

I have next config
```
 'components' => [
        'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'localhost',
            'port' => 6379,
            'database' => 2,
        ],
```

and also i set different volume for param database, but anyway all data writes to a db0 (https://prnt.sc/rw3piq)

maybe i need to set number of database more in another place? or where my mistake?

Thanks

**Comment by samdark** [comment]
That's weird. Can you debug `Connection::open()` method? According to code and tests it should properly select database.

**Comment by DesRodman** [comment]
Made debug and it works...
Sorry, but looks like i copied source code from samples with unlegal symbols
