### ISSUE TITLE
Connect to Redis Cluster in Yandex Cloud

### ISSUE THREAD

**Issue by abpopov** [yiisoft/yii2-redis#211]
Hello!
Is there any way to connect to Yandex Cloud

$sentinels = ['tcp://host:port'];
$options = [
    'replication' => 'sentinel',
    'service' => 'service_name',
    'parameters' => [
        'password' => '<password>'
    ]
];

**Comment by abpopov** [comment]
We want to use 
https://cloud.yandex.ru/docs/managed-redis/operations/cluster-create
and in Yandex cloud help I got

`sudo pear channel-discover pear.nrk.io
sudo pear install nrk/Predis
Пример кода:
require 'Predis/Autoloader.php';
Predis\Autoloader::register();

$sentinels = ['tcp://server:port];
$options = [
    'replication' => 'sentinel',
    'service' => 'cluster_name',
    'parameters' => [
        'password' => '<password>'
    ]
];
$client = new Predis\Client($sentinels, $options);

$client->set('foo', 'bar');`


Can I use yii2-redis to connect to this Yandex cloud redid cluster?

**Comment by samdark** [comment]
I think so. Why not?

**Comment by abpopov** [comment]
How?) 

Connection config of yii2-redis

`'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'localhost',
            'port' => 6379,
            'database' => 0,
        ],`

**Comment by abpopov** [comment]
I see in YandexCloud FAQ that we can use direct connection.
Is there any way to connect via Redis Sentinel?

**Comment by samdark** [comment]
Checked it. I have no idea if current code is suitable. It [supports multiple replicas](https://github.com/yiisoft/yii2-redis/blob/master/src/Cache.php#L60) but I have no idea on how to work with sentinel on the low level.

**Comment by samdark** [comment]
Here it is: https://github.com/yiisoft/yii2-redis/issues/45
