### ISSUE TITLE
redis->set函数传第第三个参数为数组时，并不支持，报错executeCommand

### ISSUE THREAD

**Issue by tanjhysj0** [yiisoft/yii2-redis#218]
代码如下

`Yii::$app->redis->set("key","value",['nx','ex'=>1])`
本来原生redis是完全可以这样执行的，就是实现setnx的同时来设置过期时间，但是在这里却招到了拒绝
 `message:mb_strlen() expects parameter 1 to be string,array give in common\\extension\\redis\\Connection.php:101`

**Comment by bizley** [comment]
Shouldn't it be `Yii::$app->redis->set("key","value", ['nx', 'ex', '1'])`?
