### ISSUE TITLE
Add Redis AUTH username support

### ISSUE THREAD

**Issue by rvkulikov** [yiisoft/yii2-redis#223]
In version 6 of redis, support for [ACL](https://redis.io/topics/acl) was introduced.  
Now you can authenticate using the [login / password](https://redis.io/commands/auth) pair.  
Adding support to a package should be easy.

**Comment by rvkulikov** [comment]
Whoa, `cebe/jenkins-test-docker` docker images are not building.
Wheezy debian dist are no longer supported.  
Which major redis versions should be covered with tests?
So it is necessary to rewrite dockerfiles required redis versions support, pass all tests, and then send PR with ACL support, am I right?

@samdark

**Comment by samdark** [comment]
We use uses: superchargejs/redis-github-action@1.1.0 via github actions.

**Comment by rvkulikov** [comment]
Не удалось доставить ваше письмо адресату, так почта ***@***.*** является ловушкой --джокера--,
ваш письмо была перенаправлено в мусорное ведро в отделе службы безопасности почтового сервера.

Ладно, спокойно.
Вы написали мне по рабочему вопросу на личную почту.
По рабочим вопросам пишите мне на почту ***@***.***
Ваше письмо было переслано на мою рабочую почту, так что дублировать письмо не надо.
Но, блин, пишите на рабочую.
Рабочая - для работы.
