### ISSUE TITLE
Doesn't work with Heroku Redis (TLS required, Redis 6+)

### ISSUE THREAD

**Issue by timkelty** [yiisoft/yii2-redis#224]
Production plans of Heroku Redis now require a TLS connection: https://devcenter.heroku.com/articles/heroku-redis#create-a-new-instance

However, enabling via `useSSL => true` does not work with these Redis instances.

### What steps will reproduce the problem?
- Configure redis component with Heroku Redis 6+.
- `useSSL => true`

### What's expected?
Connection should work.

### What do you get instead?
```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.40
| PHP version      | 7.4

**Comment by samdark** [comment]
Configure your PHP properly:

1. Download https://curl.haxx.se/ca/cacert.pem
2. Specify path to the file in `php.ini`, `openssl.cafile="/path/to/cacert.pem"`.
3. Restart PHP.

**Comment by timkelty** [comment]
Thanks @samdark, I'll give it a try!

FWIW, it looks like Heroku just made this change recently, so it will likely become relevant to anyone running Yii/Craft on Heroku Redis.

**Comment by SerotoninaAbad** [comment]
Hi @timkelty. Did you manage to find a solution to that problem in Heroku?

**Comment by timkelty** [comment]
@SerotoninaAbad Ended up going with the dumb/easy solution: ditch Heroku Redis and use their "Redis To Go" add-on, which doesn't require tls.

**Comment by boboldehampsink** [comment]
> Configure your PHP properly:
> 
> 1. Download https://curl.haxx.se/ca/cacert.pem
> 2. Specify path to the file in `php.ini`, `openssl.cafile="/path/to/cacert.pem"`.
> 3. Restart PHP.

@dzuelke is this something that needs to be done in the buildpack?

**Comment by boboldehampsink** [comment]
Can this be worked around now that https://github.com/yiisoft/yii2-redis/pull/227 is released?

**Comment by michaelroper** [comment]
Got bitten by this one today too, and can't use @timkelty's solution.. has anyone else managed to get a connection working to Heroku Redis?

**Comment by boboldehampsink** [comment]
Got it working by using this in the config:

``
            'useSSL' => true,
            'contextOptions' => [
                'ssl' => [
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                ],
            ],
```

**Comment by samdark** [comment]
As I previously said, https://github.com/yiisoft/yii2-redis/issues/224#issuecomment-780703158 should be done instead of turning off peer verification.

**Comment by boboldehampsink** [comment]
@samdark that is only if you have control over the php installation

**Comment by bizley** [comment]
Guys, it's 2021... Change your provider. Anyway, this should be continued at forum if at all.
