### ISSUE TITLE
Call for HSET got HMSET instead

### ISSUE THREAD

**Issue by Stairdeck** [yiisoft/yii2-redis#229]
If I use this:

```php
$redis->executeCommand('HSET', [
    'mail_tokens', $user->id, $token, 'EX' => 60*60*24
]);
```
Got this: 

```json
{
    "name": "Database Exception",
    "message": "Redis error: ERR wrong number of arguments for HMSET\nRedis command was: HSET mail_tokens 3 QXY_7-kn2NbN4NQXo0mS5CwdG3oPJNU- 86400",
    "code": "",
    "type": "yii\\db\\Exception",
    "file": "C:\\OpenServer\\domains\\c\\vendor\\yiisoft\\yii2-redis\\src\\Connection.php",
    "line": 828,
    "stack-trace": [
        "#0 C:\\OpenServer\\domains\\c\\vendor\\yiisoft\\yii2-redis\\src\\Connection.php(796): yii\\redis\\Connection->parseResponse()",
        "#1 C:\\OpenServer\\domains\\c\\vendor\\yiisoft\\yii2-redis\\src\\Connection.php(779): yii\\redis\\Connection->sendCommandInternal()",
        "#2 C:\\OpenServer\\domains\\c\\models\\forms\\RegistrationForm.php(86): yii\\redis\\Connection->executeCommand()",
...
```

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.14
| PHP version      | 7.4.14
| Operating system | Windows 10 (Open Server 5.3.8)

**Comment by samdark** [comment]
Looks like a pure bug 👍

**Comment by samdark** [comment]
Hmm... wait. `Redis command was: HSET mail_tokens 3 QXY_7-kn2NbN4NQXo0mS5CwdG3oPJNU- 86400` means the correct command was issued.

**Comment by Stairdeck** [comment]
> 
> 
> Hmm... wait. `Redis command was: HSET mail_tokens 3 QXY_7-kn2NbN4NQXo0mS5CwdG3oPJNU- 86400` means the correct command was issued.

Yes, but exception throws and redis empty

**Comment by samdark** [comment]
Would you please try `HSET mail_tokens 3 QXY_7-kn2NbN4NQXo0mS5CwdG3oPJNU- 86400` directly on Redis without using PHP?

**Comment by Stairdeck** [comment]
All is ok, problem was with ttl. Redis does not support this on hashes only if it not top. Sorry for wasting time.

**Comment by samdark** [comment]
No problem. You're welcome.
