### ISSUE TITLE
Unknown Method – yii\base\UnknownMethodException. Calling unknown method: yii\redis\Connection::sAdd()

### ISSUE THREAD

**Issue by qvink** [yiisoft/yii2-redis#24]
Exception in /home/dev/donever-yii2/vendor/yiisoft/yii2/base/Component.php at line 285.

$redisCommand = strtoupper(Inflector::camel2words($name, false));
Why use Inflector::camel2words ?  Is it a bug?

**Comment by samdark** [comment]
It's not a bug, it was designed like that. I guess the method name would be `sadd()`.

**Comment by cebe** [comment]
this is intentional, camel2words is used for redis commands that have two words, e.g. http://redis.io/commands/client-list

**Comment by xuwuqiang** [comment]
i also meet this problem..... i change the source code like this....

```php
//$redisCommand = strtoupper(Inflector::camel2words($name, false));
if (in_array($redisCommand = strtoupper ($name), $this->redisCommands)) {
    return $this->executeCommand($redisCommand, $params);
} else {
    $redisCommand = strtoupper(Inflector::camel2words($name, false));
    return parent::__call($redisCommand, $params);
}
```
