### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 9835256 bytes)

### ISSUE THREAD

**Issue by ruikc** [yiisoft/yii2-redis#242]
### What steps will reproduce the problem?
Allowed memory size of 134217728 bytes exhausted (tried to allocate 9835256 bytes)
executeCommand($name,$params=[]),params=[] is to long;but not control the number

### What's expected?
control the number to write

### What do you get instead?
control the params number to write. why not use the php redis extend?

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.42.1
| PHP version      | 7.2
| Operating system | centos

**Comment by ruikc** [comment]
When does the issue occur?
![image](https://user-images.githubusercontent.com/7445875/150042926-791ad11a-3506-4faf-b173-1156ee66fca7.png)
the $command is not limit the total length, big data may out the memory limit
What do you see?
![origin_img_v2_496163e0-9a68-49e3-ac6e-4d2cf0814f5g](https://user-images.githubusercontent.com/7445875/150043084-de12c3bb-b9cc-47c1-8d32-c4c334cc9369.png)
What was the expected result?
support the big data to write to redis
Can you supply us with a stacktrace? (optional)
Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)

**Comment by samdark** [comment]
We should not impose any limit since raising memory limit of PHP should allow larger strings.
