### ISSUE TITLE
Big cost of preliminary implode params for parseResponse error

### ISSUE THREAD

**Issue by alx-xc** [yiisoft/yii2-redis#264]
### What steps will reproduce the problem?
mget with big list of keys

### What's expected?
Expected: normal execution time, like with older versions (like 2.0.7)

### What do you get instead?
Instead: excecution time increased from 2s to 30+s
when yii-redis updated from 2.0.7 to 2.0.13

### Additional info
implode called for every call of parseResponse
we have a lot of executions for Multi-bulk replies

![photo_2023-10-18 19 34 41](https://github.com/yiisoft/yii2-redis/assets/2317227/414a6823-fae5-455d-989f-f6a1ade275cc)

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13 (version of yii2-redis)
| PHP version      | 7.4.3
| Operating system | ubuntu

**Comment by bizley** [comment]
Indeed, it should not be done like that, I can see it was changed in 2.0.11. Could you prepare PR fixing it?

**Comment by rob006** [comment]
https://github.com/yiisoft/yii2-redis/pull/265
