### ISSUE TITLE
ERR invalid expire time in SETEX

### ISSUE THREAD

**Issue by vyachin** [yiisoft/yii2-redis#33]
![2015 09 08-22 09 15](https://cloud.githubusercontent.com/assets/1744721/9744740/58103c2a-5676-11e5-8c64-2b1a0504e4b8.jpg)

**Comment by cebe** [comment]
32bit integer overflow...
maybe cast to int is not needed so we may be able to avoid the problem.

**Comment by cebe** [comment]
I do not see a good way to fix. Not casting to int can break if the result is not an integer number. You need to keep using smaller timeouts on 32 bit systems or use 64bit system if you need large expiry time.
