### ISSUE TITLE
Connection class can't be extended

### ISSUE THREAD

**Issue by AlexanderDobrev** [yiisoft/yii2-redis#48]
Hello recently i tried to extend Connection class and currently is not possible because the property that is used for streaming data have "private" visibility.

```
/**
 * @var resource redis socket connection
 */
private $_socket;
```

Also the method that is parsing server response is private, and cannot be overriden.

```
/**
 * @param string $command
 * @return mixed
 * @throws Exception on error
 */
private function parseResponse($command)
{
```

Im suggesting visibility of this property and method to be changed to 'protected'.

**Comment by cebe** [comment]
why do you need to extend it?

**Comment by AlexanderDobrev** [comment]
@cebe I want to add additional functionality that will automatically try to reconnect to redis when connection closed because network issue. In my case i need to override executeCommand method to catch Exceptions and handle them.

**Comment by cebe** [comment]
can't you do it like this:

```php
public function executeCommand($name, $params = [])
{
     try {
        return parent::executeCommand($name, $params);
     } catch(\Exception $e) {
         // TODO try to reconnect
         return parent::executeCommand($name, $params);
    }
}
```
?

**Comment by uu-myheart** [comment]
@yii-bot 傻逼
