### ISSUE TITLE
Redis error: ERR Protocol error: invalid bulk length Redis command was: hmset Array

### ISSUE THREAD

**Issue by wanghaozi** [yiisoft/yii2-redis#49]
with the demo usage:
`
$result = $redis->hmset(['test_collection', 'key1', 'val1', 'key2', 'val2']);
`
got the errors:
`
Database Exception – yii\db\Exception
Redis error: ERR Protocol error: invalid bulk length
Redis command was: hmset Array
`
fix the invoke codes with : 
`
$result = $redis->hmset(['test_collection', 'key1', 'val1', 'key2', 'val2']);
`
seems work. If the documentation is wrong , please fix it.thx

**Comment by samdark** [comment]
Umm... I see no difference:

```php
 $result = $redis->hmset(['test_collection', 'key1', 'val1', 'key2', 'val2']); // demo 
 $result = $redis->hmset(['test_collection', 'key1', 'val1', 'key2', 'val2']); // your proposed fix
```

**Comment by wanghaozi** [comment]
sorry for the confusion.
the usage should be 
`
$result = $redis->hmset('test_collection', 'key1', 'val1', 'key2', 'val2');
`
