### ISSUE TITLE
How to get the max id of column id?

### ISSUE THREAD

**Issue by Chienle** [yiisoft/yii2-redis#51]
How to get the max id of column id?
I can only get the biggest id is 99, although in my Redis about 1,000 records with id from 1-1000

**Comment by SilverFire** [comment]
Please, post your code.

**Comment by Chienle** [comment]
@SilverFire , please see  http://pastebin.com/wZsvavgf

**Comment by Chienle** [comment]
Sorry, I've check again, error by function rules in my redis model, thank for support !
