### ISSUE TITLE
redis function `del` return value

### ISSUE THREAD

**Issue by ftwbzhao** [yiisoft/yii2-redis#52]
execute `DEL` return Boolean
https://github.com/yiisoft/yii2-redis/blob/master/Cache.php#L198

**Return Value**
> Integer reply: The number of keys that were removed.

http://redis.io/commands/del#return-value

Why are returns a Boolean type?

**Comment by cebe** [comment]
it is called with exactly one key so the number could either be 1 or 0, which is converted to the boolean value expected by the base class. https://github.com/yiisoft/yii2/blob/master/framework/caching/Cache.php#L410
