### ISSUE TITLE
Problems with Session handling

### ISSUE THREAD

**Issue by djbuch** [yiisoft/yii2-redis#59]
Hello,

I have some very bizarre problems, when I enable Redis session on my app, sometimes after some ajax requests (my page loads different contents with ajax about 10 to 20 ajax requests during page life) the app logs out alone, my app also has a system to switch users (it logs in another identity). All those things are working akwardly (sometimes the user is not switched, sometimes a log out, sometimes the user is switched during the ajax loads) when I use redis session. When I go back to file session none of these problems persists.

Have you any idea ?

Regards,
David

**Comment by samdark** [comment]
Please use forums for questions. This is too vague to be in issue tracker which is about bugs and feature requests. Thanks!
