### ISSUE TITLE
Bug in 2.05 version

### ISSUE THREAD

**Issue by alexk984** [yiisoft/yii2-redis#67]
Failed to connect server always

`exception 'yii\base\ErrorException' with message 'fwrite() expects
parameter 1 to be resource, null given' in
/var/www/utrener/vendor/yiisoft/yii2-redis/Connection.php:392`

When I revert version to 2.04 it started to work again

**Comment by cebe** [comment]
can you show your config?

**Comment by alexk984** [comment]
'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'aaa.ru',
            'port' => 6379,
            'database' => 0,
        ]

**Comment by cebe** [comment]
also, the stack trace of the error please.

**Comment by alexk984** [comment]
2016-04-27 23:47:04 [-][-][-][error][yii\base\ErrorException:2]
exception 'yii\base\ErrorException' with message 'fwrite() expects
parameter 1 to be resource, null given' in
/var/www/utrener/vendor/yiisoft/yii2-redis/Connection.php:392
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2,
'fwrite() expect...', '/var/www/utrene...', 392, Array)
#1 /var/www/utrener/vendor/yiisoft/yii2-redis/Connection.php(392):
fwrite(NULL, '*2\r\n$4\r\nrpop\r\n$...')
#2 /var/www/utrener/vendor/yiisoft/yii2-redis/Connection.php(355):
yii\redis\Connection->executeCommand('rpop', Array)
#3 /var/www/utrener/console/controllers/OnlineController.php(76):
yii\redis\Connection->__call('rpop', Array)
#4 /var/www/utrener/console/controllers/OnlineController.php(76):
yii\redis\Connection->rpop('query_log')
#5 /var/www/utrener/console/controllers/OnlineController.php(67):
console\controllers\OnlineController->saveLogs()
#6 [internal function]:
console\controllers\OnlineController->actionIndex()
#7 /var/www/utrener/vendor/yiisoft/yii2/base/InlineAction.php(55):
call_user_func_array(Array, Array)
#8 /var/www/utrener/vendor/yiisoft/yii2/base/Controller.php(154):
yii\base\InlineAction->runWithParams(Array)
#9 /var/www/utrener/vendor/yiisoft/yii2/console/Controller.php(108):
yii\base\Controller->runAction('', Array)
#10 /var/www/utrener/vendor/yiisoft/yii2/base/Module.php(454):
yii\console\Controller->runAction('', Array)
#11 /var/www/utrener/vendor/yiisoft/yii2/console/Application.php(167):
yii\base\Module->runAction('online', Array)
#12 /var/www/utrener/vendor/yiisoft/yii2/console/Application.php(143):
yii\console\Application->runAction('online', Array)
#13 /var/www/utrener/vendor/yiisoft/yii2/base/Application.php(375):
yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /var/www/utrener/yii(31): yii\base\Application->run()
#15 {main}

**Comment by cebe** [comment]
reproduced, issue was introduced by #37

**Comment by cebe** [comment]
Fixed, thanks for reporting!
