### ISSUE TITLE
Check isActive when Redis server down

### ISSUE THREAD

**Issue by oyajiro** [yiisoft/yii2-redis#7]
If i use Yii::$app->redis->open(); when redis server down. I want to switch to alternative DB. So i use Yii::$app->redis->open(); in try catch structure. After it, if i check on Yii::$app->redis->isActive it's true, even if redis not working(or not installed)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-redis/pull/6

**Comment by cebe** [comment]
fixed by #106
