### ISSUE TITLE
Yii2 - Reddis - Backend session gives null data

### ISSUE THREAD

**Issue by jaiminmoslake7020** [yiisoft/yii2-redis#76]
### What steps will reproduce the problem?

I have used redis 

`       'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'localhost',
            'port' => 6379,
            'database' => 0,
        ],

        'cache' => [
            'class' => 'yii\redis\Cache',
            'redis' => [
                'hostname' => 'localhost',
                'port' => 6379,
                'database' => 0,
            ]
        ],
        'session' => [
            'class' => 'yii\redis\Session',
            'redis' => [
                'hostname' => 'localhost',
                'port' => 6379,
                'database' => 0,
            ]
        ],  `

I have used  https://github.com/nenad-zivkovic/yii2-advanced-template  Yii2 Template.  

Sessions in frontend working good i get all the data stored in sessions.

But same session is not working in backend.

Ex. : User Logged in frontend , when i try to fetch user_id with Yii::$app()->user->id , i get correct value in frontend. But i do get null value in backend. at the same time.. if there are two different tabs in browser open. frontend gives correct user_id but backedn gives null data. 

### What's expected?
Backedn session nshould give same data. Like Yii::$app()->user->id should give correct value. 

### What do you get instead?
null value.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |     "yiisoft/yii2": "2.*",
| PHP version      | PHP Version 5.6.20
| Operating system | Windows 10
|Redis-x64-3.2.100.msi|   

Windows 10,
Redis-x64-3.2.100.msi  for windows, 
PHP Version 5.6.20
XAMPP Control Panel Version: 3.2.2

**Comment by samdark** [comment]
Which backend and frontend do you mean? There are none in the template you've mentioned.

**Comment by jaiminmoslake7020** [comment]
https://github.com/nenad-zivkovic/yii2-advanced-template  Sorry about that i am talking aboutthis template.

**Comment by jaiminmoslake7020** [comment]
I updated my question.   My further testing says ... Backend and Frontend both sessions are working . But They are not shared sessions. Like if i store something bin backedn i can use it in backend . But if i store something in frontend then i can not use that in backend.   

Before this we were using DB for sessions and at that time sessions were shared between frontend and backend. But in redis it is not.

So is there a config do i have to make.

Like any variable or is it at Redis. 



For backend
 [keyPrefix] => 0fd66

For frontend
  [keyPrefix] => 6714b


While printing session object in both.

**Comment by jaiminmoslake7020** [comment]
SOlved.

I have to set keyPrefix to a some value so they do not have different values. Working now.

$keyPrefix public property
A string prefixed to every cache key so that it is unique. If not set, it will use a prefix generated from \yii\redis\Application::id. You may set this property to be an empty string if you don't want to use key prefix. It is recommended that you explicitly set this property to some static value if the cached data needs to be shared among multiple applications.
