### ISSUE TITLE
deleteAll with strict_types=1

### ISSUE THREAD

**Issue by cmazx** [yiisoft/yii2-redis#93]
### What steps will reproduce the problem?
Call deleteAll with "IN" condition
\yii\redis\ActiveRecord::deleteAll(['in','id',[1,2,3]);
### What's expected?
Count of deleted in return.
### What do you get instead?
[yii\base\ErrorException] array_intersect(): Argument #1 is not an array

### Additional info
In \yii\yii2-redis\ActiveQuery.php:355
called $modelClass::isPrimaryKey($this->where[1]) 
isPrimaryKey first argument must be array (by phpdoc)

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.10
| PHP version      | 7.0.4(strict_types=1)
| Operating system | Ubuntu

**Comment by samdark** [comment]
What do you mean by "with strict_types=1"? How to reproduce that?

**Comment by cmazx** [comment]
declare strict types on, in enter script
`declare(strict_types = 1);`

**Comment by samdark** [comment]
In `index.php`?

**Comment by cmazx** [comment]
Yep. When php will check incoming attributes for array_intersect(array $array1, array $array2, array $_ = null)

**Comment by cmazx** [comment]
Even if no strict_types, problem exist. array_intersect require array attributes.
