### ISSUE TITLE
Frequent "Connection Timed Out" Error

### ISSUE THREAD

**Issue by iadj** [yiisoft/yii2-redis#95]
I'm using a redis configuration on my yii2 installation, and everything appears to be working properly. However, my error logs displays an error happening frequently in production:  `Failed to open redis DB connection ( [ip address]:6379, database=0): 110 - Connection timed out`.

In a few days there will be thousands of this error in my error log.

There appears to be enough RAM available on the redis server, and the website seems to be working properly in production.

**Comment by cebe** [comment]
can you provide the full error including the stack trace?

**Comment by iadj** [comment]
Unfortunately there doesn't appear to be a stack trace. This is the full
error being logged.

**Comment by cebe** [comment]
In which logfile does that appear? does not seem to be the yii application log then.

**Comment by iadj** [comment]
@cebe Correction, here's the stack trace (the errors come paired with 2 different errors. One with stack trace and one with just the error message):
```
	
yii\db\Exception: Failed to open DB connection. in C:\web\vendor\yiisoft\yii2-redis\Connection.php:294
Stack trace:
#0 C:\web\vendor\yiisoft\yii2-redis\Connection.php(383): yii\redis\Connection->open()
#1 C:\web\vendor\yiisoft\yii2-redis\Cache.php(102): yii\redis\Connection->executeCommand('GET', Array)
#2 C:\web\vendor\yiisoft\yii2\caching\Cache.php(114): yii\redis\Cache->getValue('809e5c25cde9c9e...')
#3 C:\web\common\components\keyStorage\KeyStorage.php(74): yii\caching\Cache->get('809e5c25cde9c9e...')
#4 C:\web\frontend\config\web.php(106): common\components\keyStorage\KeyStorage->get('frontend.mainte...')
#5 [internal function]: {closure}(Object(yii\web\Application))
#6 C:\web\common\components\maintenance\Maintenance.php(50): call_user_func(Object(Closure), Object(yii\web\Application))
#7 C:\web\vendor\yiisoft\yii2\base\Application.php(320): common\components\maintenance\Maintenance->bootstrap(Object(yii\web\Application))
#8 C:\web\vendor\yiisoft\yii2\web\Application.php(69): yii\base\Application->bootstrap()
#9 C:\web\vendor\yiisoft\yii2\base\Application.php(272): yii\web\Application->bootstrap()
#10 C:\web\vendor\yiisoft\yii2\base\Object.php(107): yii\base\Application->init()
#11 C:\web\vendor\yiisoft\yii2\base\Application.php(205): yii\base\Object->__construct(Array)
#12 C:\web\frontend\web\index.php(22): yii\base\Application->__construct(Array)
#13 {main}
Additional Information:
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by collinswang** [comment]
yes, i have four server that's  same situtation. 
random show me 110 - Connection timed out.
how to fix it ?
anyone can help me ??
VERSION: 

- 2.0.5

===============================

2017-03-03 17:13:30 [192.168.0.66][-][-][error][yii\redis\Connection] Failed to open redis DB connection (192.168.0.55:7001, database=2): 110 - Connection timed out
2017-03-03 17:13:30 [192.168.0.66][-][-][error][yii\db\Exception] exception 'yii\db\Exception' with message 'Failed to open DB connection.' in /home/web/web/vendor/yiisoft/yii2-redis/Connection.php:281
Stack trace:
#0 /home/web/web/vendor/yiisoft/yii2-redis/Connection.php(370): yii\redis\Connection->open()
#1 /home/web/web/common/modules/cforum/components/DataForumThread.php(856): yii\redis\Connection->executeCommand('EXISTS', Array)

**Comment by iadj** [comment]
Pinging @cebe, I posted a logfile [here](https://github.com/yiisoft/yii2-redis/issues/95#issuecomment-280334090). Do you see anything that might be the issue?

**Comment by cebe** [comment]
no idea, sorry. Does this happpen under high load or normal operation? Is a firewall involved?

**Comment by iadj** [comment]
@cebe Load isn't particularly high. Redis is running on a separate server, but it's not blocked and running almost flawlessly except for this frequent error.

**Comment by maxcl730** [comment]
@iadj   Mybe your system has many “TIME_WAIT” connections , Their number probably reached the maximum setting (tcp_max_tw_buckets) .

**Comment by iadj** [comment]
@maxcl730 This sounds like it could be the issue. Do you happen to know how to fix this? Google hasn't been my friend with this issue. This also might be handy for the yii2-redis doc.

**Comment by samdark** [comment]
Doesn't look like framework issue. If you'll find out how to configure server/redis in order to mitigate the issue, please open pull request or issue with doc changes. Thank you!
